# Generated by Django 5.0 on 2024-02-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='username',
            name='text',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='username',
            name='text2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='website',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
