# Generated by Django 5.0 on 2024-02-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_username_date_added_alter_username_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='text',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='username',
            name='text2',
            field=models.CharField(max_length=16),
        ),
    ]
