# Generated by Django 5.0.2 on 2024-04-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_username_text_alter_username_text2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='username',
            name='text2',
            field=models.CharField(max_length=200),
        ),
    ]
